### ISSUE TITLE
Phone margin mobile

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/plumbelt#3]
De ce avem aici : body.frontpage #call_me_now margin right ala mare ? Mi se pare ca se vede aiurea .

**Comment by claudiuvertistudio** [comment]
@ineagu crezi ca e mai ok asa? https://docs.google.com/a/vertistudio.com/file/d/0B-5bubkEZeL-Z0t1UF9nZzl0VGM/edit?usp=drivesdk

**Comment by ineagu** [comment]
pare ok in screenshot
